### ISSUE TITLE
Issue whilst compiling sources

### ISSUE THREAD

**Issue by iancornelius** [sonyxperiadev/device-sony-pdx206#6]
```
vendor/qcom/opensource/media/sm8250/libc2dcolorconvert/C2DColorConverter.cpp:555
:20: error: use of undeclared identifier 'C2D_COLOR_FORMAT_420_P010'; did you me
an 'C2D_COLOR_FORMAT_420_TP10'?
            return C2D_COLOR_FORMAT_420_P010;
                   ^~~~~~~~~~~~~~~~~~~~~~~~~
                   C2D_COLOR_FORMAT_420_TP10
vendor/qcom/opensource/display/libcopybit/c2d2.h:211:5: note: 'C2D_COLOR_FORMAT_
420_TP10' declared here
    C2D_COLOR_FORMAT_420_TP10     = 191,
    ^
1 error generated.
```
Issue only occurs whilst building for pdx206

```
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=11
TARGET_PRODUCT=aosp_xqas52
TARGET_BUILD_VARIANT=eng
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-2a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-2a
TARGET_2ND_CPU_VARIANT=generic
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.11.0-16-generic-x86_64-Ubuntu-21.04
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=RQ2A.210305.006
OUT_DIR=out
PRODUCT_SOONG_NAMESPACES=device/sony/common device/sony/edo vendor/qcom/opensour
ce/core-utils
============================================
```

**Comment by iancornelius** [comment]
Okay, so adjusting the file as per the recommendation in the error, solves the issue and I am able to compile sources further. Not 100% sure on what this would affect on the outcome as I am still compiling as I am writing this comment.

**Potential Fix**
Change `C2D_COLOR_FORMAT_420_P010` to `C2D_COLOR_FORMAT_420_TP10`

**Comment by MarijnS95** [comment]
Qcom made it so that we need newer sources for Edo devices (PDX203, 206) that are only compatible with kernel 4.19 but not 4.14. For that we need to have two checkouts, but no-one has found the time to set that up yet.

To fix this, check out the [`display`](https://github.com/sonyxperiadev/hardware-qcom-display) repo (where this _wrong_ suggested fix was made - it'll give you tons of conflicts in the end) on `aosp/LA.UM.9.12.r1`, and do the same for [`commonsys-intf-display`](https://github.com/sonyxperiadev/vendor-qcom-opensource-commonsys-intf-display).

**Comment by jerpelea** [comment]
the easy fix (for now) for this issue is to initialize the tree using the following commands
mkdir ~/android
cd ~/android
repo init -u https://android.googlesource.com/platform/manifest -b **android-11.0.0_r32**
cd .repo
git clone https://github.com/sonyxperiadev/local_manifests
cd local_manifests
git checkout **master**
cd ../..

**Comment by MarijnS95** [comment]
Please use what @jerpelea describes instead. That also checks out the `device/sony/common` repo on `master` which is _also_ required for the new display repos to work.

**Comment by iancornelius** [comment]
Thanks for your assistance on this, I will follow what @jerpelea has suggested.
